name:                lens-typelevel
version:             0.1.0.0
github:              "mstksg/lens-typelevel"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/lens-typelevel#readme>

ghc-options:
- -Wall
- -Wcompat

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - singletons >= 2.5
  - profunctors
  - microlens

# executables:
#   lens-typelevel-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lens-typelevel

# tests:
#   lens-typelevel-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lens-typelevel
